// <auto-generated>
// Rewired Constants
// This list was generated on 5/26/2021 9:51:11 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace Mahou.Input {
    public static partial class Action {
        // Default
        // Player
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Movement X")]
        public const int Movement_X = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Movement Y")]
        public const int Movement_Y = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Action0")]
        public const int Camera_X = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Camera Y")]
        public const int Camera_Y = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Action0")]
        public const int Lockon = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Jump")]
        public const int Jump = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Attack")]
        public const int Attack = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Performance Mode")]
        public const int Performance_Mode = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Abilities")]
        public const int Abilities = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Action0")]
        public const int Ability_1 = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Action1")]
        public const int Ability_2 = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Action2")]
        public const int Ability_3 = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Action3")]
        public const int Ability_4 = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Dash")]
        public const int Dash = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Player", friendlyName = "Parry")]
        public const int Parry = 14;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int Player = 1;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player")]
        public const int Player0 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
